import type { Brief } from './brief.js';

/**
 * A brief as a file somebody else can read (doc 08, export).
 *
 * `renderBrief` produces the text the board shows on screen, where the frame
 * around it supplies the context. A file has no frame. Pasted into a pull
 * request or a standup note it arrives with no card, no board and no date, and
 * a reader who does not know when it was generated cannot tell a current
 * summary from a stale one - which is the original problem, exported.
 *
 * It is also not quite markdown. The blast radius list is indented two spaces,
 * so every filename collapses into one run-on paragraph the moment anything
 * renders it. On screen that is invisible; in a pull request it is the whole
 * section destroyed.
 *
 * So the export is rendered separately: real list markers, and a provenance
 * footer stating what this is and when it was taken.
 */

export interface ExportInput {
  readonly brief: Brief;
  readonly cardId: string;
  readonly boardName: string;
  readonly generatedAt: number;
}

/** Lines the on-screen brief indents for alignment rather than for meaning. */
function asListItem(line: string): string {
  const trimmed = line.trimStart();
  if (trimmed === '') return '';
  return line.length === trimmed.length ? trimmed : `- ${trimmed}`;
}

export function briefToMarkdown(input: ExportInput): string {
  const lines = [`# ${input.brief.headline}`, ''];

  for (const section of input.brief.sections) {
    lines.push(`## ${section.title}`, '');

    for (const line of section.lines) {
      lines.push(asListItem(line));
    }

    lines.push('');
  }

  // Said last and said plainly. The brief is derived from the ledger and is
  // true as of a moment; a reader who cannot see which moment will either
  // trust a stale summary or distrust a current one.
  lines.push(
    '---',
    '',
    `Generated by Gorilla from board "${input.boardName}" on ` +
      `${new Date(input.generatedAt).toISOString()}, for card ${input.cardId}.`,
    'Derived from the card ledger, which remains the record. Regenerate rather than edit.',
  );

  return lines.join('\n').trimEnd() + '\n';
}

/** A filename an operator can find again among thirty downloads. */
export function exportFilename(cardTitle: string, cardId: string): string {
  const slug = cardTitle
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 48);

  return `${slug === '' ? 'card' : slug}-${cardId.slice(0, 8)}.md`;
}
